Repository checkupjs/checkup, pull requests merged in 2020-03, with the labels that each got.

#55 task(linting): Adding linting plugins to extend lint checks
  .eslintrc
  package.json
  packages/cli/__tests__/tasks-test.ts
  packages/cli/src/index.ts
  packages/cli/src/task-list.ts
  packages/core/src/base-task.ts
  packages/core/src/file-searcher-task.ts
  packages/core/src/loaders/plugin-loader.ts
  packages/core/src/searchers/file-searcher.ts
  packages/core/src/utils/get-package-json.ts
  packages/core/src/utils/ui.ts
  packages/plugin-default/src/tasks/project-info-task.ts
  packages/plugin-ember/__tests__/__snapshots__/dependencies-task-test.ts.snap
  packages/plugin-ember/__tests__/dependencies-task-test.ts
  packages/plugin-ember/src/results/dependencies-task-result.ts
  packages/plugin-ember/src/tasks/dependencies-task.ts
  packages/plugin-ember/src/tasks/types-task.ts
  packages/plugin-ember/src/utils/project.ts
  packages/test-helpers/src/checkup-fixturify-project.ts
  packages/test-helpers/src/ember-cli-fixturify-project.ts
  yarn.lock
Labels: internal

#61 Adding use cases and personas into the spec
  SPEC.md
Labels: documentation

#75 Refactoring task registration to simplify
  packages/cli/__tests__/index-test.ts
  packages/cli/__tests__/priority-map-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/src/priority-map.ts
  packages/cli/src/task-list.ts
  packages/core/src/base-task-result.ts
  packages/core/src/base-task.ts
  packages/core/src/index.ts
  packages/core/src/types/index.ts
  packages/plugin-default/src/hooks/register-tasks.ts
  packages/plugin-default/src/results/project-info-task-result.ts
  packages/plugin-default/src/tasks/project-info-task.ts
  packages/plugin-ember/src/hooks/register-tasks.ts
  packages/plugin-ember/src/results/dependencies-task-result.ts
  packages/plugin-ember/src/results/ember-project-task-result.ts
  packages/plugin-ember/src/results/types-task-result.ts
  packages/plugin-ember/src/tasks/dependencies-task.ts
  packages/plugin-ember/src/tasks/ember-project-task.ts
  packages/plugin-ember/src/tasks/types-task.ts
  packages/test-helpers/src/plugin.ts
Labels: internal

#60 Refactor Checkup Configuration Loading
  packages/cli/src/index.ts
  packages/core/__tests__/configuration/__snapshots__/checkup-config-service-test.ts.snap
  packages/core/__tests__/configuration/checkup-config-service-test.ts
  packages/core/__tests__/configuration/cosmiconfig-service-test.ts
  packages/core/__tests__/configuration/get-search-loader-test.ts
  packages/core/package.json
  packages/core/src/configuration/checkup-config-service.ts
  packages/core/src/configuration/cosmiconfig-service.ts
  packages/core/src/configuration/loaders/get-search-loader.ts
  packages/core/src/index.ts
  packages/core/src/types/index.ts
  packages/core/src/utils/get-config.ts
  yarn.lock
Labels: enhancement, internal

#83 feat(plugin-ember-octane): Create plugin-ember-octane
  .gitignore
  packages/cli/package.json
  packages/plugin-ember-octane/README.md
  packages/plugin-ember-octane/__tests__/__fixtures__/sample-octane-eslint-report.json
  packages/plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
  packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/plugin-ember-octane/__tests__/tasks/octane-migration-status-task-test.ts
  packages/plugin-ember-octane/__tests__/tsconfig.json
  packages/plugin-ember-octane/jest.config.js
  packages/plugin-ember-octane/package.json
  packages/plugin-ember-octane/src/hooks/register-tasks.ts
  packages/plugin-ember-octane/src/index.ts
  packages/plugin-ember-octane/src/results/index.ts
  packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
  packages/plugin-ember-octane/src/tasks/index.ts
  packages/plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  packages/plugin-ember-octane/tsconfig.json
  yarn.lock
Labels: checkup-task, enhancement

#86 feat(plugin-ember-octane): Output completion info to JSON
  packages/plugin-ember-octane/__tests__/__fixtures__/sample-octane-eslint-report.json
  packages/plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
  packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
Labels: checkup-task, enhancement

#80 Add config flag to optionally pass explicit config path to cli
  packages/cli/README.md
  packages/cli/__tests__/__snapshots__/index-test.ts.snap
  packages/cli/__tests__/index-test.ts
  packages/cli/src/index.ts
  packages/core/__tests__/configuration/get-filepath-loader-test.ts
  packages/core/src/configuration/loaders/get-filepath-loader.ts
  packages/core/src/configuration/loaders/get-search-loader.ts
  packages/core/src/index.ts
Labels: enhancement

#95 ESLint console output
  packages/plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
  packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
Labels: checkup-task, enhancement

#123 Add template lint to plugin-ember-octane
  packages/plugin-ember-octane/__tests__/__fixtures__/sample-octane-template-lint-report.json
  packages/plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
  packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/plugin-ember-octane/__tests__/tasks/octane-migration-status-task-test.ts
  packages/plugin-ember-octane/package.json
  packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
  packages/plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  tsconfig.json
  yarn.lock
Labels: checkup-task, internal

#127 Adding plugin generator
  packages/cli/README.md
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-plugin-test.ts
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
  packages/cli/templates/src/plugin/README.md.ejs
  packages/cli/templates/src/plugin/jest.config.js
  packages/cli/templates/src/plugin/package.json.ejs
  packages/cli/templates/src/plugin/src/hooks/register-tasks.js.ejs
  packages/cli/templates/src/plugin/src/hooks/register-tasks.ts.ejs
  packages/cli/templates/src/plugin/src/index.js.ejs
  packages/cli/templates/src/plugin/src/index.ts.ejs
  packages/cli/templates/src/plugin/src/tasks/index.js.ejs
  packages/cli/templates/src/plugin/src/tasks/index.ts.ejs
  packages/cli/templates/src/plugin/src/types/index.js.ejs
  packages/cli/templates/src/plugin/src/types/index.ts.ejs
  packages/cli/templates/src/plugin/tsconfig.json
  packages/cli/templates/src/task/__tests__/task.js.ejs
  packages/cli/templates/src/task/__tests__/task.ts.ejs
  packages/cli/templates/src/task/src/results/task-result.js.ejs
  packages/cli/templates/src/task/src/results/task-result.ts.ejs
  packages/cli/templates/src/task/src/tasks/task.js.ejs
  packages/cli/templates/src/task/src/tasks/task.ts.ejs
  packages/test-helpers/src/index.ts
  packages/test-helpers/src/test-root.ts
Labels: enhancement, generators

#103 Add Config Init Command
  packages/cli/README.md
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
  packages/cli/__tests__/generators/generate-config-test.ts
  packages/cli/checkup-report-2020-03-24-11-51-31.pdf
  packages/cli/checkup-report-2020-03-24-11-55-47.pdf
  packages/cli/src/commands/generate.ts
  packages/cli/src/generators/config.ts
  packages/core/__tests__/configuration/get-initialization-loader-test.ts
  packages/core/src/configuration/loaders/get-initialization-loader.ts
  packages/core/src/index.ts
  yarn.lock
Labels: enhancement

#140 Refactor types for plugin-ember-octane
  packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
  packages/plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  packages/plugin-ember-octane/src/types/ember-template-lint.ts
  packages/plugin-ember-octane/src/types/index.ts
Labels: checkup-task, internal

#148 Plugin Ember Octane: Refactor linting constructs into their own files/
  packages/plugin-ember-octane/src/linters/ember-template-lint.ts
  packages/plugin-ember-octane/src/linters/es-lint.ts
  packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
  packages/plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  packages/plugin-ember-octane/src/types/ember-template-lint.ts
  packages/plugin-ember-octane/src/types/index.ts
  packages/plugin-ember-octane/src/utils/lint-configs.ts
  packages/plugin-ember-octane/src/utils/task-configs.ts
  packages/plugin-ember-octane/src/utils/transformers.ts
Labels: checkup-task, internal

#163 Fix NaN bugs in lint reports
  packages/plugin-ember-octane/__tests__/__fixtures__/non-migrated-barebones-eslint-report.json
  packages/plugin-ember-octane/__tests__/__fixtures__/non-migrated-barebones-template-lint-report.json
  packages/plugin-ember-octane/__tests__/utils/transformers-test.ts
  packages/plugin-ember-octane/src/utils/task-configs.ts
  packages/plugin-ember-octane/src/utils/transformers.ts
Labels: bug

#166 Fixing checkup-meta-task's use of shorthash
  packages/cli/__tests__/tasks/checkup-meta-task-test.ts
  packages/cli/src/tasks/checkup-meta-task.ts
  packages/cli/tsconfig.json
  packages/cli/types/shorthash.d.ts
Labels: bug
