Repository checkupjs/checkup, pull requests merged in 2020-06, with the labels that each got.

#469 Adding task that checks how many times ember template-lint is disabled
  packages/checkup-plugin-ember/__tests__/template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/package.json
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember/src/results/template-lint-disable-task-result.ts
  packages/checkup-plugin-ember/src/tasks/template-lint-disable-task.ts
Labels: checkup-task

#487 Externalizing programmatic invocation of checkup
  packages/cli/__tests__/commands/run-error-test.ts
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/src/index.ts
  packages/cli/src/run-command.ts
Labels: enhancement

#486 Render the task category in stdout
  packages/checkup-plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/src/results/template-lint-disable-task-result.ts
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/src/results/eslint-disable-task-result.ts
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/reporters-test.ts
  packages/cli/__tests__/tasks/lines-of-code-task-test.ts
  packages/cli/src/reporters.ts
  packages/cli/src/tasks/lines-of-code-task.ts
  packages/core/src/types/tasks.ts
  packages/core/src/utils/ui.ts
Labels: enhancement

#516 Extending ember-template-lint config type definition
  packages/core/src/types/ember-template-lint.ts
Labels: enhancement

#517 Bumping walksync and using new API to fix #473
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/utils/get-paths.ts
  yarn.lock
Labels: bug

#505 Adding actions for eslint-summary task
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/checkup-plugin-javascript/src/results/eslint-summary-task-result.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
Labels: checkup-task

#515 Ensuring generators can generate into a specific path
  packages/cli/__tests__/__utils__/generate-plugin.ts
  packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-config-test.ts
  packages/cli/__tests__/generators/generate-plugin-test.ts
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/generators/base-generator.ts
Labels: bug, requires-doc-update

#518 Fixes generator error handling. Fix bug with short plugin names
  packages/cli/src/commands/generate.ts
  packages/cli/src/generators/config.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
  packages/core/src/config/index.ts
Labels: bug

#520 Refactors tasks to have correct isolation between Task and TaskResult classes
  packages/checkup-plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/checkup-plugin-ember-octane/__tests__/tasks/octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/results/octane-migration-status-task-result.ts
  packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
  packages/checkup-plugin-ember/src/results/ember-dependencies-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-in-repo-addons-engines-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-test-types-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-types-task-result.ts
  packages/checkup-plugin-ember/src/results/template-lint-disable-task-result.ts
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-ember/src/tasks/template-lint-disable-task.ts
  packages/checkup-plugin-javascript/src/results/eslint-disable-task-result.ts
  packages/checkup-plugin-javascript/src/results/eslint-summary-task-result.ts
  packages/checkup-plugin-javascript/src/results/outdated-dependencies-task-result.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/__tests__/__utils__/mock-task-result.ts
  packages/cli/__tests__/__utils__/mock-tasks.ts
  packages/cli/__tests__/reporters-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/__tests__/task-result-comparator-test.ts
  packages/cli/src/results/lines-of-code-task-result.ts
  packages/cli/src/tasks/lines-of-code-task.ts
  packages/core/src/types/tasks.ts
  packages/core/src/utils/data-transformers.ts
Labels: breaking, internal

#519 Adding count of files checkup operated on to the project-meta task
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/results/project-meta-task-result.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/core/src/utils/get-paths.ts
Labels: checkup-task, enhancement

#521 Adding strong types for register hooks arguments
  packages/checkup-plugin-ember-octane/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-javascript/src/hooks/register-tasks.ts
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/package.json
  packages/cli/templates/src/plugin/src/hooks/register-tasks.ts.ejs
  packages/core/src/types/tasks.ts
  packages/test-helpers/src/checkup-fixturify-project.ts
  packages/test-helpers/src/index.ts
  packages/test-helpers/src/plugin.ts
Labels: breaking, generators

#526 Adds a specific type for a config value
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/core/__tests__/action-list-test.ts
  packages/core/__tests__/base-task-test.ts
  packages/core/__tests__/config-test.ts
  packages/core/src/action-list.ts
  packages/core/src/base-task.ts
  packages/core/src/config/index.ts
  packages/core/src/index.ts
  packages/core/src/types/config.ts
Labels: breaking
