Repository checkupjs/checkup, pull requests merged in 2020-04, with the labels that each got.

#185 Fixing missing deps in core
  packages/cli/package.json
  packages/core/package.json
Labels: bug

#206 Updating scripts to ensure lib is cleaned before build
  packages/cli/package.json
  packages/core/package.json
  packages/parser-eslint/package.json
  packages/plugin-ember-octane/package.json
  packages/plugin-ember/package.json
  packages/test-helpers/package.json
Labels: internal

#210 Adding report data infrastructure for generating HTML/PDF reports
  packages/cli/__tests__/__snapshots__/pdf-test.ts.snap
  packages/cli/src/helpers/pdf.ts
  packages/cli/src/static/components/graded-table.hbs
  packages/cli/src/static/components/numerical-card.hbs
  packages/cli/src/static/components/pie-chart.hbs
  packages/cli/src/static/components/table.hbs
  packages/cli/src/static/report-template.hbs
  packages/core/src/index.ts
  packages/core/src/pdf-components/graded-table-data.ts
  packages/core/src/pdf-components/numerical-card-data.ts
  packages/core/src/pdf-components/pdf-component-data.ts
  packages/core/src/pdf-components/pie-chart-data.ts
  packages/core/src/pdf-components/table-data.ts
  packages/core/src/report-components/graded-table-data.ts
  packages/core/src/report-components/numerical-card-data.ts
  packages/core/src/report-components/pie-chart-data.ts
  packages/core/src/report-components/report-component-data.ts
  packages/core/src/report-components/table-data.ts
  packages/core/src/types/index.ts
  yarn.lock
Labels: internal

#238 Updating generators
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/templates/src/plugin/package.json.ejs
  packages/cli/templates/src/task/src/results/task-result.js.ejs
  packages/cli/templates/src/task/src/results/task-result.ts.ejs
Labels: generators

#256 Updating task ordering to sort by category then priority
  packages/cli/__tests__/__snapshots__/task-list-test.ts.snap
  packages/cli/__tests__/__utils__/mock-task-result.ts
  packages/cli/__tests__/__utils__/mock-task.ts
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/priority-map-test.ts
  packages/cli/__tests__/reporters-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/src/task-list.ts
  packages/core/src/base-task-result.ts
  packages/core/src/index.ts
  packages/core/src/utils/task-result-comparator.ts
  packages/test-helpers/src/index.ts
  packages/test-helpers/src/task.ts
Labels: internal

#267 Adding tests for meta-task-list
  packages/cli/__tests__/__snapshots__/meta-task-list-test.ts.snap
  packages/cli/__tests__/__snapshots__/task-list-test.ts.snap
  packages/cli/__tests__/__utils__/mock-meta-task.ts
  packages/cli/__tests__/__utils__/mock-task.ts
  packages/cli/__tests__/__utils__/mock-tasks.ts
  packages/cli/__tests__/meta-task-list-test.ts
  packages/cli/__tests__/priority-map-test.ts
  packages/cli/__tests__/task-list-test.ts
Labels: internal

#268 Cleaning up documentation
  README.md
  docs/SPEC.md
  packages/cli/README.md
Labels: documentation

#280 Cleanup of config generator
  packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
  packages/cli/__tests__/generators/generate-config-test.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/generators/config.ts
  packages/core/__tests__/configuration/__snapshots__/checkup-config-service-test.ts.snap
  packages/core/__tests__/configuration/checkup-config-service-test.ts
  packages/core/src/configuration/checkup-config-service.ts
  packages/core/src/types/configuration.ts
Labels: enhancement
