Repository checkupjs/checkup, pull requests merged in 2020-08, with the labels that each got.

#587 Converting eslint-disable task to schema
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/src/tasks/template-lint-disable-task.ts
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/src/results/eslint-disable-task-result.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/cli/src/generators/task.ts
  packages/core/__tests__/searchers/file-searcher-test.ts
  packages/core/src/ast/ast-transformer.ts
  packages/core/src/ast/ast-traverser.ts
  packages/core/src/index.ts
  packages/core/src/searchers/file-searcher.ts
  packages/test-helpers/src/filter-result-data.ts
  packages/test-helpers/src/index.ts
Labels: breaking

#604 Standardizing task names within plugins for consistency.
  packages/checkup-plugin-ember-octane/__tests__/tasks/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember-octane/__tests__/tasks/ember-octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember-octane/src/results/ember-octane-migration-status-task-result.ts
  packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember/src/results/ember-template-lint-disable-task-result.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
Labels: breaking

#606 Cleanup of task name standardization
  packages/checkup-plugin-ember-octane/__tests__/tasks/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember-octane/__tests__/tasks/ember-octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
Labels: internal

#607 Add linting to plugins generated by plugin generator
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/generate-plugin-test.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/templates/src/plugin/.eslintignore.ejs
  packages/cli/templates/src/plugin/.eslintrc.js.ejs
  packages/cli/templates/src/plugin/.eslintrc.ts.ejs
  packages/cli/templates/src/plugin/.gitignore.ejs
  packages/cli/templates/src/plugin/.prettierrc.js.ejs
  packages/cli/templates/src/plugin/package.json.js.ejs
  packages/cli/templates/src/plugin/package.json.ts.ejs
Labels: enhancement

#608 First pass at removing toConsole by creating a console reporter
  packages/checkup-plugin-ember-octane/__tests__/tasks/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember-octane/__tests__/tasks/ember-octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/results/ember-octane-migration-status-task-result.ts
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/src/results/ember-dependencies-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-in-repo-addons-engines-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-template-lint-disable-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-test-types-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-types-task-result.ts
  packages/checkup-plugin-javascript/__tests__/__snapshots__/eslint-summary-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/checkup-plugin-javascript/src/results/eslint-disable-task-result.ts
  packages/checkup-plugin-javascript/src/results/eslint-summary-task-result.ts
  packages/checkup-plugin-javascript/src/results/outdated-dependencies-task-result.ts
  packages/cli/__tests__/__utils__/mock-meta-task-result.ts
  packages/cli/__tests__/__utils__/mock-task-result.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/reporters-test.ts
  packages/cli/__tests__/tasks/lines-of-code-task-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/reporters.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/reporters/get-actions.ts
  packages/cli/src/reporters/get-reporter.ts
  packages/cli/src/reporters/json-reporter.ts
  packages/cli/src/results/lines-of-code-task-result.ts
  packages/cli/src/results/project-meta-task-result.ts
  packages/cli/src/types/index.ts
  packages/cli/templates/src/task/__tests__/task.js.ejs
  packages/cli/templates/src/task/__tests__/task.ts.ejs
  packages/cli/templates/src/task/src/results/task-result.js.ejs
  packages/cli/templates/src/task/src/results/task-result.ts.ejs
  packages/core/__tests__/builders-test.ts
  packages/core/src/base-task-result.ts
  packages/core/src/data/builders.ts
  packages/core/src/types/checkup-result.ts
  packages/core/src/types/tasks.ts
Labels: breaking

#610 Adding actions registration system to decouple from task results
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-ember/package.json
  packages/checkup-plugin-ember/src/actions/ember-template-lint-disable-actions.ts
  packages/checkup-plugin-ember/src/actions/ember-test-types-actions.ts
  packages/checkup-plugin-ember/src/hooks/register-actions.ts
  packages/checkup-plugin-ember/src/results/ember-dependencies-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-template-lint-disable-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-test-types-task-result.ts
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/checkup-plugin-javascript/package.json
  packages/checkup-plugin-javascript/src/actions/eslint-disable-actions.ts
  packages/checkup-plugin-javascript/src/actions/eslint-summary-actions.ts
  packages/checkup-plugin-javascript/src/actions/outdated-dependency-actions.ts
  packages/checkup-plugin-javascript/src/hooks/register-actions.ts
  packages/checkup-plugin-javascript/src/results/eslint-disable-task-result.ts
  packages/checkup-plugin-javascript/src/results/eslint-summary-task-result.ts
  packages/checkup-plugin-javascript/src/results/outdated-dependencies-task-result.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/reporters/get-actions.ts
  packages/cli/src/reporters/json-reporter.ts
  packages/cli/src/types/index.ts
  packages/core/__tests__/actions-evaluator-test.ts
  packages/core/src/actions/actions-evaluator.ts
  packages/core/src/actions/registered-actions.ts
  packages/core/src/index.ts
  packages/core/src/parsers/registered-parsers.ts
  packages/core/src/types/tasks.ts
Labels: breaking

#611 Deleting all TaskResult classes
  packages/checkup-plugin-ember-octane/__tests__/tasks/ember-octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/results/ember-octane-migration-status-task-result.ts
  packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/src/actions/ember-template-lint-disable-actions.ts
  packages/checkup-plugin-ember/src/actions/ember-test-types-actions.ts
  packages/checkup-plugin-ember/src/results/ember-dependencies-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-in-repo-addons-engines-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-template-lint-disable-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-test-types-task-result.ts
  packages/checkup-plugin-ember/src/results/ember-types-task-result.ts
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/checkup-plugin-javascript/src/actions/eslint-disable-actions.ts
  packages/checkup-plugin-javascript/src/actions/eslint-summary-actions.ts
  packages/checkup-plugin-javascript/src/actions/outdated-dependency-actions.ts
  packages/checkup-plugin-javascript/src/results/eslint-disable-task-result.ts
  packages/checkup-plugin-javascript/src/results/eslint-summary-task-result.ts
  packages/checkup-plugin-javascript/src/results/outdated-dependencies-task-result.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/__tests__/__snapshots__/task-list-test.ts.snap
  packages/cli/__tests__/__utils__/mock-task-result.ts
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/__tests__/task-result-comparator-test.ts
  packages/cli/__tests__/tasks/lines-of-code-task-test.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/generators/task.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/reporters/json-reporter.ts
  packages/cli/src/results/lines-of-code-task-result.ts
  packages/cli/src/task-result-comparator.ts
  packages/cli/src/tasks/lines-of-code-task.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/cli/src/types/index.ts
  packages/cli/templates/src/task/__tests__/task.js.ejs
  packages/cli/templates/src/task/__tests__/task.ts.ejs
  packages/cli/templates/src/task/src/results/task-result.js.ejs
  packages/cli/templates/src/task/src/results/task-result.ts.ejs
  packages/cli/templates/src/task/src/tasks/task.js.ejs
  packages/cli/templates/src/task/src/tasks/task.ts.ejs
  packages/core/src/actions/registered-actions.ts
  packages/core/src/base-task.ts
  packages/core/src/types/checkup-result.ts
  packages/core/src/types/tasks.ts
Labels: breaking

#612 Removal of meta property in favor of flat properties
  packages/checkup-plugin-ember-octane/__tests__/tasks/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-javascript/__tests__/__snapshots__/eslint-summary-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/__tests__/__snapshots__/task-list-test.ts.snap
  packages/cli/__tests__/__utils__/mock-task-result.ts
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/meta-task-list-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/__tests__/task-result-comparator-test.ts
  packages/cli/__tests__/tasks/lines-of-code-task-test.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/task-list.ts
  packages/cli/src/task-result-comparator.ts
  packages/cli/src/tasks/lines-of-code-task.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/cli/templates/src/task/src/tasks/task.js.ejs
  packages/cli/templates/src/task/src/tasks/task.ts.ejs
  packages/core/__tests__/base-task-test.ts
  packages/core/src/base-task-result.ts
  packages/core/src/base-task.ts
  packages/core/src/index.ts
  packages/core/src/types/checkup-result.ts
  packages/core/src/types/tasks.ts
Labels: breaking

#615 task: Adding v8-compile-cache to speed up CLI perf
  packages/cli/bin/run
  packages/cli/package.json
  yarn.lock
Labels: enhancement

#616 Adding missing dependency
  packages/core/package.json
Labels: bug

#617 Updates --tasks flag back to --tasks, and allows multiple invocations
  packages/cli/README.md
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-error-test.ts
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/task-list.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/core/src/types/cli.ts
  packages/test-helpers/src/get-task-context.ts
Labels: bug

#628 Adding actions generator
  packages/cli/__tests__/generators/__snapshots__/generate-actions-test.ts.snap
  packages/cli/__tests__/generators/generate-actions-test.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/generators/actions.ts
  packages/cli/src/generators/base-generator.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
  packages/cli/templates/src/actions/src/actions/actions.js.ejs
  packages/cli/templates/src/actions/src/actions/actions.ts.ejs
  packages/cli/templates/src/actions/src/hooks/register-actions.js.ejs
  packages/cli/templates/src/actions/src/hooks/register-actions.ts.ejs
Labels: enhancement, generators

#633 Adding dependency on `--format json` for `outputFile` flag
  .eslintrc
  packages/cli/src/commands/run.ts
Labels: enhancement

#645 Prioritizing cli args for turning tasks on
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-test.ts
  packages/core/src/base-task.ts
Labels: internal

#648 [bugfix] Fixing eslint-summary task so it only lints files passed in
  packages/checkup-plugin-javascript/__tests__/__snapshots__/eslint-summary-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
Labels: bug

#647 Fixing checkup-result types and ensuring results use typed output
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/get-checkup-result.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/reporters/json-reporter.ts
  packages/cli/src/results/project-meta-task-result.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/cli/src/types/index.ts
  packages/core/src/types/checkup-result.ts
Labels: internal

#649 Bug fix for ember-test-types-task
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
Labels: bug

#650 Adding task timings
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/package.json
  packages/cli/src/commands/run.ts
  packages/cli/src/get-checkup-result.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/task-list.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/core/src/types/checkup-result.ts
  yarn.lock
Labels: enhancement

#652 Fixing missing dep in checkup-plugin-javascript
  packages/checkup-plugin-javascript/package.json
Labels: bug

#655 Ensuring errors render fullyQualifiedTaskNames
  packages/cli/__tests__/task-list-test.ts
  packages/cli/src/task-list.ts
Labels: internal

#657 Fixing typos
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/src/actions/eslint-disable-actions.ts
  packages/cli/src/reporters/console-reporter.ts
Labels: bug

#646 First steps at standardizing console reporter - implementing SummaryResult reporters
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/checkup-plugin-javascript/src/actions/outdated-dependency-actions.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/core/src/types/checkup-result.ts
  packages/core/src/utils/ui.ts
Labels: internal

#669 Bumping eslint-plugin-ember
  .github/workflows/ci-build.yml
  packages/checkup-plugin-ember-octane/package.json
  yarn.lock
Labels: bug
