Repository checkupjs/checkup, pull requests merged in 2020-11, with the labels that each got.

#751 Bug fixes
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/run-command.ts
  packages/core/src/data/builders.ts
  packages/core/src/types/tasks.ts
Labels: bug

#771 Moving consoleMessage to properties
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
  packages/cli/src/reporters/console-reporter.ts
  packages/core/src/data/builders.ts
Labels: bug

#753 Adding HTTP support for config loading
  package.json
  packages/cli/src/commands/run.ts
  packages/core/__tests__/__fixtures__/.checkuprc.json
  packages/core/__tests__/config-test.ts
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/config.ts
  packages/core/src/index.ts
  yarn.lock
Labels: enhancement

#778 Changes file extension of outputFile to sarif
  packages/cli/src/reporters/json-reporter.ts
Labels: breaking

#780 Exporting getReporters API in order to provide reporting for Node API
  packages/cli/src/index.ts
Labels: enhancement

#781 Fixing SARIF log so that each location is mapped to one Result
  packages/checkup-plugin-ember-octane/__tests__/tasks/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/src/actions/ember-template-lint-disable-actions.ts
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/src/actions/eslint-disable-actions.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/__tests__/__utils__/mock-meta-task-result.ts
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/meta-task-list-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/get-log.ts
  packages/cli/src/reporters/console-reporter.ts
  packages/cli/src/results/project-meta-task-result.ts
  packages/cli/src/types/index.ts
  packages/cli/templates/src/task/src/tasks/task.js.ejs
  packages/cli/templates/src/task/src/tasks/task.ts.ejs
  packages/core/src/base-task.ts
  packages/core/src/data/builders.ts
  packages/core/src/data/formatters.ts
  packages/core/src/index.ts
  packages/core/src/types/tasks.ts
Labels: bug
