Repository checkupjs/checkup, pull requests merged in 2020-05, with the labels that each got.

#358 Refactoring tasks to include taskContext and task options"
  packages/checkup-plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/checkup-plugin-ember-octane/__tests__/tasks/octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/cli/__tests__/__utils__/mock-meta-task-result.ts
  packages/cli/__tests__/commands/__snapshots__/run-error-test.ts.snap
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-error-test.ts
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/__tests__/tasks/checkup-meta-task-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/base-meta-task-result.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/generators/task.ts
  packages/cli/src/reporters.ts
  packages/cli/src/tasks/checkup-meta-task.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/cli/src/types/index.ts
  packages/cli/templates/src/plugin/src/hooks/register-tasks.js.ejs
  packages/cli/templates/src/plugin/src/hooks/register-tasks.ts.ejs
  packages/core/__tests__/configuration/__snapshots__/checkup-config-service-test.ts.snap
  packages/core/src/base-task.ts
  packages/core/src/file-searcher-task.ts
  packages/core/src/index.ts
  packages/core/src/types/cli.ts
  packages/core/src/types/runtime-types.ts
  packages/core/src/types/tasks.ts
  packages/test-helpers/src/checkup-plugin-project.ts
  packages/test-helpers/src/get-task-context.ts
  packages/test-helpers/src/index.ts
  packages/test-helpers/static/templates/register-tasks.hbs
Labels: internal

#373 Part 3 of task context refactoring: Passing normalized plugin names to tasks
  packages/checkup-plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
  packages/checkup-plugin-ember-octane/__tests__/tasks/octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/cli/__tests__/__utils__/mock-tasks.ts
  packages/cli/__tests__/commands/run-error-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/tasks/checkup-meta-task-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/generators/task.ts
  packages/cli/src/tasks/checkup-meta-task.ts
  packages/cli/templates/src/plugin/src/hooks/register-tasks.js.ejs
  packages/cli/templates/src/plugin/src/hooks/register-tasks.ts.ejs
  packages/cli/templates/src/task/__tests__/task.js.ejs
  packages/cli/templates/src/task/__tests__/task.ts.ejs
  packages/core/__tests__/base-task-test.ts
  packages/core/__tests__/configuration/checkup-config-service-test.ts
  packages/core/__tests__/utils/plugin-name-test.ts
  packages/core/package.json
  packages/core/src/base-task.ts
  packages/core/src/configuration/checkup-config-service.ts
  packages/core/src/file-searcher-task.ts
  packages/core/src/index.ts
  packages/core/src/utils/plugin-name.ts
  yarn.lock
Labels: internal

#387 [task] - number of Ember engines and addons
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember/src/results/ember-in-repo-addons-engines-task-result.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/templates/src/task/__tests__/task.js.ejs
  packages/cli/templates/src/task/__tests__/task.ts.ejs
  packages/core/src/utils/get-package-json.ts
  packages/test-helpers/src/ember-cli-fixturify-project.ts
Labels: checkup-task

#401 [task] Updates Outdated Dependency output to use barchart
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/tasks/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/cli/src/results/outdated-dependencies-task-result.ts
  packages/core/src/utils/ui.ts
Labels: checkup-task

#402 Freezing task context to prevent mutation
  packages/cli/src/commands/run.ts
  packages/core/src/types/tasks.ts
Labels: internal

#403 Add ability to specify location of output for meta tasks
  packages/cli/__tests__/__utils__/mock-meta-task-result.ts
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/tasks/checkup-meta-task-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/reporters.ts
  packages/cli/src/results/checkup-meta-task-result.ts
  packages/cli/src/results/project-meta-task-result.ts
  packages/cli/src/types/index.ts
Labels: internal

#404 Changes `checkup run` to default to `checkup` (without `run`)
  CONTRIBUTING.md
  packages/checkup-plugin-ember-octane/README.md
  packages/cli/README.md
  packages/cli/src/commands/run.ts
  packages/cli/src/index.ts
Labels: enhancement

#379 [task] TODOs
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/tasks/todos-task-test.ts
  packages/cli/package.json
  packages/cli/src/commands/run.ts
  packages/cli/src/helpers/repository.ts
  packages/cli/src/results/todos-task-result.ts
  packages/cli/src/tasks/todos-task.ts
  packages/core/__tests__/.DS_Store
  packages/core/__tests__/searchers/file-searcher-test.ts
  packages/core/src/index.ts
  packages/core/src/searchers/file-searcher.ts
  packages/core/src/utils/exec.ts
  yarn.lock
Labels: checkup-task

#424 Standardize flags
  packages/cli/README.md
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/reporters-test.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/helpers/ui-report.ts
  packages/cli/src/reporters.ts
  packages/core/__tests__/base-task-test.ts
  packages/core/src/types/cli.ts
  packages/core/src/types/tasks.ts
  packages/test-helpers/src/get-task-context.ts
Labels: internal, requires-doc-update

#386 [task] - Ember test types
  checkup.code-workspace
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/src/eslint/rules/test-types.js
  packages/checkup-plugin-ember/src/eslint/tests/test-types.test.js
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-ember/src/results/ember-test-types-task-result.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/types/index.ts
  packages/checkup-plugin-ember/src/utils/lint-configs.ts
  packages/checkup-plugin-ember/src/utils/transformers.ts
  packages/checkup-plugin-ember/tsconfig.json
  packages/cli/src/types/index.ts
  packages/core/src/index.ts
  packages/core/src/utils/data-transformers.ts
  packages/core/src/utils/ui.ts
  packages/test-helpers/src/index.ts
  packages/test-helpers/src/validate-chart-results.ts
Labels: checkup-task

#429 Removing cosmiconfig in favor of simpler structure.
  packages/cli/__tests__/commands/__snapshots__/run-error-test.ts.snap
  packages/cli/__tests__/commands/run-error-test.ts
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
  packages/cli/__tests__/generators/generate-config-test.ts
  packages/cli/__tests__/tasks/checkup-meta-task-test.ts
  packages/cli/package.json
  packages/cli/src/commands/run.ts
  packages/cli/src/generators/config.ts
  packages/core/__tests__/configuration/__snapshots__/checkup-config-service-test.ts.snap
  packages/core/__tests__/configuration/checkup-config-service-test.ts
  packages/core/__tests__/configuration/cosmiconfig-service-test.ts
  packages/core/__tests__/configuration/get-filepath-loader-test.ts
  packages/core/__tests__/configuration/get-initialization-loader-test.ts
  packages/core/__tests__/configuration/get-search-loader-test.ts
  packages/core/__tests__/utils/config-test.ts
  packages/core/package.json
  packages/core/src/base-task.ts
  packages/core/src/config/config-schema.json
  packages/core/src/config/index.ts
  packages/core/src/configuration/checkup-config-service.ts
  packages/core/src/configuration/cosmiconfig-service.ts
  packages/core/src/configuration/loaders/get-filepath-loader.ts
  packages/core/src/configuration/loaders/get-initialization-loader.ts
  packages/core/src/configuration/loaders/get-search-loader.ts
  packages/core/src/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/configuration.ts
  packages/core/src/types/runtime-types.ts
  packages/core/src/types/tasks.ts
  packages/core/tsconfig.json
  packages/test-helpers/package.json
  packages/test-helpers/src/checkup-fixturify-project.ts
  yarn.lock
Labels: internal

#430 Adding paths to TaskContext and updating all tasks to use it
  packages/checkup-plugin-ember-octane/__tests__/tasks/octane-migration-status-task-test.ts
  packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/__tests__/get-paths-test.ts
  packages/cli/__tests__/tasks/checkup-meta-task-test.ts
  packages/cli/__tests__/tasks/outdated-dependencies-task-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/__tests__/tasks/todos-task-test.ts
  packages/cli/package.json
  packages/cli/src/commands/run.ts
  packages/cli/src/helpers/get-package-json.ts
  packages/cli/src/helpers/get-paths.ts
  packages/cli/src/results/todos-task-result.ts
  packages/cli/src/tasks/todos-task.ts
  packages/core/__tests__/base-task-test.ts
  packages/core/__tests__/searchers/file-searcher-test.ts
  packages/core/package.json
  packages/core/src/file-searcher-task.ts
  packages/core/src/index.ts
  packages/core/src/searchers/file-searcher.ts
  packages/core/src/types/cli.ts
  packages/core/src/types/tasks.ts
  packages/core/src/types/util.ts
  packages/test-helpers/src/checkup-fixturify-project.ts
  packages/test-helpers/src/filter-result-data.ts
  packages/test-helpers/src/get-task-context.ts
  packages/test-helpers/src/index.ts
  packages/test-helpers/src/stdout.ts
  yarn.lock
Labels: internal

#448 Gracefully handle errors in the CLI
  packages/cli/__tests__/__utils__/mock-tasks.ts
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/run-error-test.ts
  packages/cli/__tests__/meta-task-list-test.ts
  packages/cli/__tests__/reporters-test.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/bin/run
  packages/cli/src/base-command.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/meta-task-list.ts
  packages/cli/src/reporters.ts
  packages/cli/src/task-list.ts
  packages/core/__tests__/config-test.ts
  packages/core/package.json
  packages/core/src/config/index.ts
  packages/core/src/errors/checkup-error.ts
  packages/core/src/index.ts
  packages/core/src/loaders/plugin-loader.ts
  packages/core/src/types/tasks.ts
  packages/test-helpers/src/get-task-context.ts
  packages/test-helpers/src/index.ts
  packages/test-helpers/src/stdout-stderr.ts
  packages/test-helpers/src/stdout.ts
  yarn.lock
Labels: enhancement

#449 Deleting unused code related to deprecated PDF/HTML functionality
  packages/cli/__tests__/__fixtures__/report.html
  packages/cli/__tests__/__utils__/mock-pie-chart-task-result.ts
  packages/cli/__tests__/__utils__/render-partial.ts
  packages/cli/__tests__/pdf-test.ts
  packages/cli/__tests__/print-to-pdf-test.ts
  packages/cli/__tests__/report-components/numerical-card-test.ts
  packages/cli/__tests__/report-components/pie-chart-test.ts
  packages/cli/__tests__/report-components/table-test.ts
  packages/cli/package.json
  packages/cli/src/helpers/print-to-pdf.ts
  packages/cli/src/helpers/ui-report.ts
  packages/cli/static/components/numerical-card.hbs
  packages/cli/static/components/pie-chart.hbs
  packages/cli/static/components/table.hbs
  packages/cli/static/external-libraries/chart-bootstrap.css
  packages/cli/static/external-libraries/chartjs-2.9.3.min.js
  packages/cli/static/report-template.hbs
  packages/core/src/index.ts
  packages/core/src/report-components/numerical-card-data.ts
  packages/core/src/report-components/pie-chart-data.ts
  packages/core/src/report-components/report-component-data.ts
  packages/core/src/report-components/table-data.ts
  packages/core/src/types/tasks.ts
  yarn.lock
Labels: internal
