Repository checkupjs/checkup, pull requests merged in 2020-02, with the labels that each got.

#3 Adding Checkup spec
  SPEC.md
Labels: documentation

#27 Refactors Checkup and CheckupCLI classes into one
  packages/cli/src/checkup.ts
  packages/cli/src/index.ts
Labels: enhancement

#28 Adding path argument to specify directory to run in
  packages/cli/__tests__/__snapshots__/index-test.ts.snap
  packages/cli/__tests__/index-test.ts
  packages/cli/src/index.ts
  packages/core/src/base-task.ts
  packages/core/src/file-searcher-task.ts
  packages/core/src/index.ts
  packages/core/src/task-list.ts
  packages/core/src/types/index.ts
  packages/core/src/utils/get-package-json.ts
  packages/plugin-ember/__tests__/__fixtures__/addon-package.json
  packages/plugin-ember/__tests__/__fixtures__/app-package.json
  packages/plugin-ember/__tests__/__snapshots__/dependencies-task-test.ts.snap
  packages/plugin-ember/__tests__/__snapshots__/project-info-task-test.ts.snap
  packages/plugin-ember/__tests__/__snapshots__/types-task-test.ts.snap
  packages/plugin-ember/__tests__/__utils__/ember-cli-fixturify-project.ts
  packages/plugin-ember/__tests__/dependencies-task-test.ts
  packages/plugin-ember/__tests__/project-info-task-test.ts
  packages/plugin-ember/__tests__/types-task-test.ts
  packages/plugin-ember/jest.config.js
  packages/plugin-ember/package.json
  packages/plugin-ember/src/tasks/dependencies-task.ts
  packages/plugin-ember/src/tasks/project-info-task.ts
  packages/plugin-ember/src/tasks/types-task.ts
  packages/plugin-ember/src/utils/project.ts
  yarn.lock
Labels: enhancement

#29 Adding taskName and friendlyTaskName to Task
  packages/cli/__tests__/__snapshots__/index-test.ts.snap
  packages/cli/src/index.ts
  packages/core/__tests__/tasks-test.ts
  packages/core/src/base-task.ts
  packages/core/src/index.ts
  packages/core/src/tasks.ts
  packages/plugin-ember/__tests__/__snapshots__/dependencies-task-test.ts.snap
  packages/plugin-ember/__tests__/__snapshots__/project-info-task-test.ts.snap
  packages/plugin-ember/__tests__/__snapshots__/types-task-test.ts.snap
  packages/plugin-ember/src/hooks/register-tasks.ts
  packages/plugin-ember/src/results/dependencies-task-result.ts
  packages/plugin-ember/src/results/project-info-task-result.ts
  packages/plugin-ember/src/results/types-task-result.ts
  packages/plugin-ember/src/tasks/dependencies-task.ts
  packages/plugin-ember/src/tasks/project-info-task.ts
  packages/plugin-ember/src/tasks/types-task.ts
  packages/plugin-ember/src/utils/default-tasks.ts
Labels: enhancement

#42 Adding wsrun package to execute tasks in dependency order and parallel
  package.json
  yarn.lock
Labels: internal

#43 Add clean commands
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-ember/package.json
  packages/test-helpers/package.json
Labels: internal

#30 feat(core): Add Support for Plugins via Config File
  packages/cli/README.md
  packages/cli/__tests__/__snapshots__/index-test.ts.snap
  packages/cli/__tests__/index-test.ts
  packages/cli/jest.config.js
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/loaders/plugin-loader.ts
  packages/core/src/types/index.ts
  packages/core/src/utils/get-config.ts
  packages/plugin-ember/package.json
  packages/test-helpers/package.json
  packages/test-helpers/src/checkup-fixturify-project.ts
  packages/test-helpers/src/index.ts
  packages/test-helpers/src/plugin.ts
  packages/test-helpers/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#53 Add Validation to Checkup Config
  packages/cli/__tests__/__snapshots__/index-test.ts.snap
  packages/cli/__tests__/index-test.ts
  packages/core/package.json
  packages/core/src/types/index.ts
  packages/core/src/types/runtime-types.ts
  packages/core/src/utils/get-config.ts
  yarn.lock
Labels: enhancement
