Repository checkupjs/checkup, pull requests merged in 2021-04, with the labels that each got.

#910 Fixes CLI error handling by standardizing within the yargs handlers
  packages/cli/__tests__/cli-test.ts
  packages/cli/package.json
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/api/generator.ts
  packages/cli/src/checkup.ts
  packages/cli/src/extended-error.ts
  packages/cli/src/generators/actions.ts
  packages/cli/src/generators/config.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
  packages/cli/src/reporters/sarif-file-writer.ts
  packages/cli/src/reporters/verbose-console-reporter.ts
  packages/cli/src/task-errors.ts
  packages/core/package.json
  packages/core/src/config.ts
  packages/core/src/errors/checkup-error.ts
  packages/core/src/errors/error-kind.ts
  packages/core/src/index.ts
  packages/core/src/today-format.ts
  packages/core/src/utils/ui.ts
  yarn.lock
Labels: bug

#914 Removes yeoman output in tests
  packages/cli/__tests__/cli-test.ts
Labels: internal

#915 Removes chai, which is unused
  package.json
  yarn.lock
Labels: internal

#924 Removes unused APIs
  package.json
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/templates/src/task/__tests__/task.js.ejs
  packages/cli/templates/src/task/__tests__/task.ts.ejs
  packages/test-helpers/src/filter-result-data.ts
  packages/test-helpers/src/index.ts
  yarn.lock
Labels: breaking

#926 Correctly generates plugins with latest package versions
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/templates/src/plugin/package.json.js.ejs
  packages/cli/templates/src/plugin/package.json.ts.ejs
Labels: bug

#930 Exporting task runner as public API
  packages/cli/src/index.ts
Labels: bug

#934 Rename reporters to formatters and associated types/code
  packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
  packages/checkup-plugin-ember/src/formatters/ember-template-lint-summary-formatter.ts
  packages/checkup-plugin-ember/src/formatters/ember-test-types-formatter.ts
  packages/checkup-plugin-ember/src/index.ts
  packages/checkup-plugin-javascript/src/formatters/eslint-summary-formatter.ts
  packages/checkup-plugin-javascript/src/formatters/outdated-dependencies-formatter.ts
  packages/checkup-plugin-javascript/src/index.ts
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/api/registration-provider.ts
  packages/cli/src/checkup.ts
  packages/cli/src/formatters/available-tasks.ts
  packages/cli/src/formatters/formatter-utils.ts
  packages/cli/src/formatters/get-formatter.ts
  packages/cli/src/formatters/json.ts
  packages/cli/src/formatters/sarif-file-writer.ts
  packages/cli/src/formatters/summary.ts
  packages/cli/src/formatters/verbose.ts
  packages/cli/src/index.ts
  packages/cli/templates/src/actions/src/registrations/register-actions.js.ejs
  packages/cli/templates/src/actions/src/registrations/register-actions.ts.ejs
  packages/cli/templates/src/task/src/registrations/register-tasks.js.ejs
  packages/cli/templates/src/task/src/registrations/register-tasks.ts.ejs
  packages/core/src/errors/error-kind.ts
  packages/core/src/task-reporters/registered-task-reporters.ts
  packages/core/src/types/cli.ts
  packages/core/src/types/tasks.ts
Labels: breaking

#936 Ensures that empty array values are treated as undefined for task runs
  packages/cli/src/api/checkup-task-runner.ts
Labels: bug

#944 Removing output-file from CheckupTaskRunner
  packages/cli/__tests__/checkup-task-runner-test.ts
  packages/cli/src/checkup.ts
  packages/cli/src/formatters/get-formatter.ts
  packages/core/src/types/cli.ts
  packages/test-helpers/src/get-task-context.ts
Labels: breaking, internal

#945 Fixing bug in pretty formatter conditional
  packages/cli/src/formatters/pretty.ts
Labels: bug

#955 Fixes loop in ember-template-lint-parser
  packages/core/src/parsers/ember-template-lint-parser.ts
Labels: bug

#957 Improve type definition for error kind map
  packages/core/src/errors/checkup-error.ts
  packages/core/src/errors/error-kind.ts
Labels: enhancement, internal

#961 Adds ability to specify custom formatters
  packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
  packages/checkup-plugin-ember/src/formatters/ember-template-lint-summary-formatter.ts
  packages/checkup-plugin-ember/src/formatters/ember-test-types-formatter.ts
  packages/checkup-plugin-javascript/src/formatters/eslint-summary-formatter.ts
  packages/checkup-plugin-javascript/src/formatters/outdated-dependencies-formatter.ts
  packages/cli/__tests__/__fixtures__/checkup-formatter-test/index.js
  packages/cli/__tests__/__fixtures__/checkup-formatter-test/package.json
  packages/cli/__tests__/__utils__/fake-project.ts
  packages/cli/__tests__/cli-test.ts
  packages/cli/jest.config.js
  packages/cli/src/formatters/formatter-utils.ts
  packages/cli/src/formatters/get-formatter.ts
  packages/cli/src/formatters/json.ts
  packages/cli/src/formatters/pretty.ts
  packages/cli/src/formatters/summary.ts
  packages/core/src/errors/error-kind.ts
  packages/core/src/types/cli.ts
  packages/core/src/types/tasks.ts
  packages/core/src/utils/pretty-formatter-utils.ts
  packages/test-helpers/src/checkup-fixturify-project.ts
Labels: enhancement

#983 Adding @microsoft/jest-sarif for log/result validation
  .eslintrc
  package.json
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-template-lint-summary-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
  packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-octane-migration-status-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-template-lint-summary-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
  packages/checkup-plugin-ember/jest.config.js
  packages/checkup-plugin-ember/jest.setup.ts
  packages/checkup-plugin-javascript/__tests__/__snapshots__/eslint-summary-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/checkup-plugin-javascript/jest.config.js
  packages/checkup-plugin-javascript/jest.setup.ts
  packages/cli/__tests__/__utils__/sarif-match-object.ts
  packages/cli/__tests__/checkup-task-runner-test.ts
  packages/cli/__tests__/cli-test.ts
  packages/cli/jest.config.js
  packages/cli/jest.setup.ts
  yarn.lock
Labels: internal
