Repository checkupjs/checkup, pull requests merged in 2021-03, with the labels that each got.

#891 Part 1 of moving off oclif to vanilla CLI
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/cli/__tests__/cli-test.ts
  packages/cli/bin/checkup.js
  packages/cli/package.json
  packages/cli/src/api/generate.ts
  packages/cli/src/api/run.ts
  packages/cli/src/checkup.ts
  packages/test-helpers/src/checkup-fixturify-project.ts
  yarn.lock
Labels: breaking, internal

#895 Part 2 of moving off oclif to vanilla CLI
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/cli/__tests__/__utils__/generate-plugin.ts
  packages/cli/__tests__/cli-test.ts
  packages/cli/__tests__/generators/generate-actions-test.ts
  packages/cli/__tests__/generators/generate-config-test.ts
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/api/generate.ts
  packages/cli/src/api/generator.ts
  packages/cli/src/api/run.ts
  packages/cli/src/checkup.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/extended-error.ts
  packages/cli/src/generators/actions.ts
  packages/cli/src/generators/base-generator.ts
  packages/cli/src/generators/config.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
Labels: breaking, enhancement

#903 Include `filePath` as part of `ember-template-lint-parser`, update `ember-template-lint`
  packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
  packages/core/package.json
  packages/core/src/parsers/ember-template-lint-parser.ts
  yarn.lock
Labels: breaking

#906 Fixes verbose output when using generator utils in tests
  packages/cli/src/generators/task.ts
Labels: internal

#907 Speeds up tests by using local link to @checkup/core in generated plugins
  packages/cli/__tests__/__utils__/fake-project.ts
  packages/cli/__tests__/cli-test.ts
  packages/test-helpers/src/checkup-fixturify-project.ts
Labels: internal

#909 Moving registration to index
  packages/checkup-plugin-ember/src/index.ts
  packages/checkup-plugin-ember/src/registrations/register-actions.ts
  packages/checkup-plugin-ember/src/registrations/register-task-reporters.ts
  packages/checkup-plugin-ember/src/registrations/register-tasks.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/src/index.ts
  packages/checkup-plugin-javascript/src/registrations/register-actions.ts
  packages/checkup-plugin-javascript/src/registrations/register-task-reporters.ts
  packages/checkup-plugin-javascript/src/registrations/register-tasks.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/cli/__tests__/generators/__snapshots__/generate-actions-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-actions-test.ts
  packages/cli/__tests__/generators/generate-plugin-test.ts
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/api/registration-provider.ts
  packages/cli/src/generators/actions.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
  packages/cli/src/get-log.ts
  packages/cli/src/task-list.ts
  packages/cli/templates/src/plugin/README.md.ejs
  packages/cli/templates/src/plugin/package.json.js.ejs
  packages/cli/templates/src/plugin/package.json.ts.ejs
  packages/cli/templates/src/plugin/src/index.js.ejs
  packages/cli/templates/src/plugin/src/index.ts.ejs
  packages/cli/templates/src/plugin/src/registrations/.gitkeep
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/parsers/registered-parsers.ts
  packages/core/src/types/cli.ts
  packages/core/src/types/tasks.ts
  packages/test-helpers/src/get-task-context.ts
  yarn.lock
Labels: breaking
