Repository checkupjs/checkup, pull requests merged in 2021-01, with the labels that each got.

#840 Extend lint tasks with custom config
  packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
  packages/core/__tests__/__fixtures__/simple.js
  packages/core/__tests__/parsers/ember-template-lint-parser-test.ts
  packages/core/__tests__/parsers/eslint-parser-test.ts
  packages/core/package.json
  packages/core/src/parsers/ember-template-lint-parser.ts
  packages/core/src/parsers/eslint-parser.ts
  packages/core/src/types/parsers.ts
Labels: enhancement

#830 Removing meta-task as a concept, moving logic from project-meta-task into get-log
  packages/cli/__tests__/__snapshots__/meta-task-list-test.ts.snap
  packages/cli/__tests__/__utils__/mock-meta-task-result.ts
  packages/cli/__tests__/meta-task-list-test.ts
  packages/cli/__tests__/tasks/project-meta-task-test.ts
  packages/cli/src/base-meta-task-result.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/get-log.ts
  packages/cli/src/meta-task-list.ts
  packages/cli/src/results/project-meta-task-result.ts
  packages/cli/src/tasks/project-meta-task.ts
  packages/cli/src/types/index.ts
  packages/core/src/types/tasks.ts
Labels: internal

#847 Updates Octane migration task with better messages
  packages/checkup-plugin-ember-octane/__tests__/tasks/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
  packages/core/src/data/builders.ts
Labels: enhancement

#856 [bugfix] Get paths updates
  packages/cli/__tests__/commands/info-test.ts
  packages/cli/__tests__/commands/migration-test.ts
  packages/cli/package.json
  packages/cli/src/args.ts
  packages/core/__tests__/utils/get-paths-test.ts
  packages/core/package.json
  packages/core/src/utils/get-paths.ts
  yarn.lock
Labels: bug

#857 Update generators to work with new commands
  packages/cli/__tests__/generators/__snapshots__/generate-actions-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-actions-test.ts
  packages/cli/__tests__/generators/generate-plugin-test.ts
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
  packages/cli/templates/src/plugin/src/hooks/.gitkeep
  packages/cli/templates/src/task/src/hooks/register-tasks.js.ejs
  packages/cli/templates/src/task/src/hooks/register-tasks.ts.ejs
Labels: enhancement
