Repository checkupjs/checkup, pull requests merged in 2021-09, with the labels that each got.

#1064 Update list and bar component to render task result correctly.
  packages/checkup-formatter-pretty/__tests__/__fixtures__/checkup-result.sarif
  packages/checkup-formatter-pretty/__tests__/components/bar-test.tsx
  packages/checkup-formatter-pretty/__tests__/components/list-test.tsx
  packages/checkup-formatter-pretty/__tests__/components/table-test.tsx
  packages/checkup-formatter-pretty/__tests__/formatter-test.ts
  packages/checkup-formatter-pretty/__tests__/list-test.tsx
  packages/checkup-formatter-pretty/__tests__/pretty-test.tsx
  packages/checkup-formatter-pretty/__tests__/sub-components/sectioned-bar-test.tsx
  packages/checkup-formatter-pretty/src/components/bar.tsx
  packages/checkup-formatter-pretty/src/components/list.tsx
  packages/checkup-formatter-pretty/src/components/table.tsx
  packages/checkup-formatter-pretty/src/components/task-result-bar.tsx
  packages/checkup-formatter-pretty/src/components/task-result-list.tsx
  packages/checkup-formatter-pretty/src/components/utils/list.tsx
  packages/checkup-formatter-pretty/src/pretty-formatter.tsx
  packages/checkup-formatter-pretty/src/sub-components/sectioned-bar.tsx
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
Labels: internal

#1067 Upgrades version of yarn via volta
  package.json
Labels: internal

#1068 Project cleanup in preparation for 1.0
  .husky/.gitignore
  .husky/pre-commit
  package.json
  packages/core/src/data/checkup-log-parser.ts
  yarn.lock
Labels: internal

#1069 Adds endLine/endColumn to result range
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/core/__tests__/base-task-test.ts
  packages/core/src/analyzers/dependency-analyzer.ts
  packages/core/src/base-task.ts
  packages/core/src/data/lint.ts
  packages/core/src/types/dependency.ts
  packages/core/src/types/tasks.ts
Labels: enhancement

#1070 Add description to Task generator
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/src/generators/task.ts
  packages/cli/templates/src/task/src/tasks/task.js.ejs
  packages/cli/templates/src/task/src/tasks/task.ts.ejs
Labels: bug, generators

#1071 Adding type to CLI options
  packages/cli/src/checkup.ts
Labels: internal

#1066 Pretty checkup tasks' output in checkup-formatter-pretty
  packages/checkup-formatter-pretty/__tests__/__fixtures__/checkup-result.sarif
  packages/checkup-formatter-pretty/__tests__/components/list-test.tsx
  packages/checkup-formatter-pretty/__tests__/components/table-test.tsx
  packages/checkup-formatter-pretty/__tests__/formatter-test.ts
  packages/checkup-formatter-pretty/__tests__/pretty-test.tsx
  packages/checkup-formatter-pretty/package.json
  packages/checkup-formatter-pretty/src/components/list.tsx
  packages/checkup-formatter-pretty/src/components/migration.tsx
  packages/checkup-formatter-pretty/src/components/table.tsx
  packages/checkup-formatter-pretty/src/get-options.ts
  packages/checkup-formatter-pretty/src/pretty-formatter.tsx
  packages/checkup-formatter-pretty/src/sub-components/sectioned-bar.tsx
  packages/checkup-formatter-pretty/src/sub-components/task-display-name.tsx
  packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
  packages/checkup-plugin-ember/src/formatters/ember-template-lint-summary-formatter.ts
  packages/checkup-plugin-ember/src/formatters/ember-test-types-formatter.ts
  packages/checkup-plugin-ember/src/index.ts
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-javascript/src/formatters/eslint-summary-formatter.ts
  packages/checkup-plugin-javascript/src/formatters/outdated-dependencies-formatter.ts
  packages/checkup-plugin-javascript/src/index.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/core/package.json
  packages/core/src/base-task.ts
  yarn.lock
Labels: internal

#1074 Move pretty related tests to checkup-formatter-pretty
  packages/checkup-formatter-pretty/__tests__/formatter-test.ts
  packages/cli/__tests__/__fixtures__/checkup-formatter-test/index.js
  packages/cli/__tests__/__snapshots__/cli-test.ts.snap
  packages/cli/__tests__/cli-test.ts
Labels: bug

#1077 Converts built-in LOC info to task
  packages/checkup-formatter-pretty/__tests__/formatter-test.ts
  packages/checkup-formatter-pretty/__tests__/pretty-test.tsx
  packages/checkup-formatter-pretty/src/components/migration.tsx
  packages/checkup-formatter-pretty/src/components/table.tsx
  packages/checkup-formatter-pretty/src/pretty-formatter.tsx
  packages/checkup-plugin-ember/src/index.ts
  packages/checkup-plugin-javascript/__tests__/lines-of-code-task-test.ts
  packages/checkup-plugin-javascript/package.json
  packages/checkup-plugin-javascript/src/index.ts
  packages/checkup-plugin-javascript/src/tasks/lines-of-code-task.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/src/formatters/formatter-utils.ts
  packages/cli/src/formatters/pretty.ts
  packages/cli/src/generators/base-generator.ts
  packages/cli/templates/src/task/__tests__/task.js.ejs
  packages/cli/templates/src/task/__tests__/task.ts.ejs
  packages/core/__tests__/data/checkup-log-builder-test.ts
  packages/core/package.json
  packages/core/src/data/checkup-log-builder.ts
  packages/core/src/index.ts
  packages/core/src/types/checkup-result.ts
  packages/core/src/utils/pretty-formatter-utils.ts
  packages/core/src/utils/repository.ts
  packages/test-helpers/src/get-task-context.ts
Labels: breaking

#1080 Adding all-contributors
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: documentation

#1081 Upgrades yeoman dependencies to fix security issues
  package.json
  packages/cli/__tests__/__utils__/generator-utils.ts
  packages/cli/__tests__/generators/generate-actions-test.ts
  packages/cli/__tests__/generators/generate-config-test.ts
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/package.json
  packages/cli/src/generators/base-generator.ts
  packages/cli/src/generators/plugin.ts
  packages/cli/src/generators/task.ts
  yarn.lock
Labels: security

#1084 deps: Upgrading jest
  package.json
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/cli/src/checkup.ts
  yarn.lock
Labels: security

#1076 Add js doc for cli export contents
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/formatters/get-formatter.ts
  packages/core/src/types/cli.ts
Labels: documentation

#1089 Sort all package.json files
  package.json
  packages/checkup-plugin-ember/package.json
  packages/checkup-plugin-javascript/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/plugin/package.json
  packages/test-helpers/package.json
  yarn.lock
Labels: internal

#1091 Adding jsdocs for test-helpers and core APIs.
  packages/core/src/analyzers/ast-analyzer.ts
  packages/core/src/analyzers/dependency-analyzer.ts
  packages/core/src/analyzers/ember-template-lint-analyzer.ts
  packages/core/src/analyzers/eslint-analyzer.ts
  packages/core/src/analyzers/handlebars-analyzer.ts
  packages/core/src/analyzers/javascript-analyzer.ts
  packages/core/src/analyzers/json-analyzer.ts
  packages/core/src/analyzers/stylelint-analyzer.ts
  packages/core/src/analyzers/typescript-analyzer.ts
  packages/core/src/ast/ast-transformer.ts
  packages/core/src/data/checkup-log-builder.ts
  packages/core/src/data/checkup-log-parser.ts
  packages/core/src/data/filters.ts
  packages/core/src/data/formatters.ts
  packages/core/src/errors/checkup-error.ts
  packages/core/src/errors/error-kind.ts
  packages/core/src/errors/task-error.ts
  packages/core/src/index.ts
  packages/core/src/utils/exec.ts
  packages/core/src/utils/get-package-json.ts
  packages/core/src/utils/get-paths.ts
  packages/core/src/utils/get-version.ts
  packages/core/src/utils/merge-lint-config.ts
  packages/core/src/utils/plugin-name.ts
  packages/core/src/utils/repository.ts
  packages/core/src/utils/sarif-utils.ts
  packages/test-helpers/src/checkup-fixturify-project.ts
  packages/test-helpers/src/ember-cli-fixturify-project.ts
  packages/test-helpers/src/get-task-context.ts
  packages/test-helpers/src/test-root.ts
  packages/test-helpers/src/tmp-dir.ts
Labels: documentation

#1094 Fixes plugin generator not generating in custom subdirectory
  packages/cli/src/api/generator.ts
  packages/cli/src/generators/plugin.ts
Labels: bug

#1095 Remove commandType param from task generator
  packages/cli/__tests__/cli-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/__tests__/generators/generate-task-test.ts
  packages/cli/src/generators/task.ts
Labels: bug

#1096 Adding required @types packages to core
  packages/core/package.json
Labels: dependencies

#1099 Fixes invalid syntax for type output
  packages/core/src/analyzers/handlebars-analyzer.ts
  packages/core/src/analyzers/javascript-analyzer.ts
  packages/core/src/analyzers/typescript-analyzer.ts
Labels: documentation

#1100 Fixes actions generator for JavaScript
  packages/checkup-plugin-javascript/docs/tasks/lines-of-code-task.md
  packages/cli/__tests__/generators/__snapshots__/generate-actions-test.ts.snap
  packages/cli/templates/src/actions/src/actions/actions.js.ejs
Labels: bug

#1105 deps: Updating fixturify-project
  package.json
  packages/checkup-formatter-pretty/package.json
  packages/checkup-plugin-ember/package.json
  packages/checkup-plugin-javascript/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/plugin/package.json
  packages/test-helpers/package.json
  packages/test-helpers/src/checkup-fixturify-project.ts
Labels: dependencies

#1107 Ensuring global execution defaults to local if present
  packages/cli/bin/checkup.js
  packages/cli/package.json
Labels: enhancement

#1108 Extracting rule metadata from addResult
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/lines-of-code-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/__tests__/cli-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/formatters/summary.ts
  packages/cli/templates/src/task/src/tasks/task.js.ejs
  packages/cli/templates/src/task/src/tasks/task.ts.ejs
  packages/core/__tests__/base-task-test.ts
  packages/core/__tests__/data/checkup-log-builder-test.ts
  packages/core/src/base-task.ts
  packages/core/src/data/checkup-log-builder.ts
  packages/core/src/data/checkup-log-parser.ts
  packages/core/src/data/sarif-log-builder.ts
  packages/core/src/types/checkup-log.ts
  packages/core/src/types/tasks.ts
  packages/test-helpers/src/get-task-context.ts
Labels: breaking

#1109 Allows formatters to be called using a short form
  packages/cli/__tests__/cli-test.ts
  packages/cli/src/formatters/get-formatter.ts
  packages/core/__tests__/utils/normalize-package-name-test.ts
  packages/core/src/base-task.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
  packages/core/src/utils/normalize-package-name.ts
  packages/core/src/utils/plugin-name.ts
Labels: enhancement

#1110 Fixes errors in lint results causing incorrect data
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/core/src/data/lint.ts
  packages/core/src/types/tasks.ts
Labels: bug

#1112 Fixes Pretty formatter outputing empty results for all tasks
  packages/checkup-formatter-pretty/__tests__/pretty-test.tsx
  packages/checkup-formatter-pretty/src/pretty-formatter.tsx
Labels: bug

#1113 Fixes bug in get-paths where subdir segments were truncated
  packages/core/__tests__/utils/get-paths-test.ts
  packages/core/src/utils/get-paths.ts
Labels: bug
