Repository checkupjs/checkup, pull requests merged in 2021-08, with the labels that each got.

#1045 Resolves type errors when building fresh master
  tsconfig-base.json
Labels: bug

#1046 Fixes task generator to output correct new Task format
  packages/cli/__tests__/cli-test.ts
  packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
  packages/cli/templates/src/task/src/tasks/task.js.ejs
  packages/cli/templates/src/task/src/tasks/task.ts.ejs
Labels: bug

#1059 Update stylelint-analyzer.ts
  packages/core/src/analyzers/stylelint-analyzer.ts
  packages/core/src/index.ts
Labels: bug

#1060 Change other formatters to return strings
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/cli/src/checkup.ts
  packages/cli/src/formatters/json.ts
  packages/cli/src/formatters/summary.ts
  packages/core/src/data/lint.ts
  packages/core/src/types/cli.ts
Labels: enhancement

#1061 Retrofit components
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/core/__tests__/base-task-test.ts
Labels: internal
