Repository checkupjs/checkup, pull requests merged in 2021-05, with the labels that each got.

#986 Fixing bug in config code
  packages/cli/src/api/checkup-task-runner.ts
  packages/core/__tests__/config-test.ts
  packages/core/src/config.ts
  packages/core/src/index.ts
Labels: bug

#987 Updates the README to clarify the value prop
  README.md
Labels: documentation

#996 Part 1: Ensure results adhere to SARIF specifications
  packages/checkup-plugin-ember/package.json
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/utils/get-package-json.ts
  packages/core/package.json
  packages/core/src/ast/ast-transformer.ts
  packages/core/src/ast/babel-traverser.ts
  packages/core/src/ast/json-traverser.ts
  packages/core/src/ast/typescript-traverser.ts
  packages/core/src/index.ts
  packages/core/src/types/tasks.ts
  packages/test-helpers/src/get-task-context.ts
  tsconfig-base.json
  yarn.lock
Labels: breaking

#997 Part 2: Ensure results adhere to SARIF specifications
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-javascript/src/actions/outdated-dependency-actions.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  yarn.lock
Labels: breaking

#998 Fixing husky
  .husky/pre-commit
  package.json
Labels: internal

#999 Standardize analyzers
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/__tests__/checkup-task-runner-test.ts
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/api/registration-provider.ts
  packages/cli/src/generators/actions.ts
  packages/cli/src/generators/task.ts
  packages/core/__tests__/analyzers/ember-template-lint-analyzer-test.ts
  packages/core/__tests__/analyzers/eslint-analyzer-test.ts
  packages/core/__tests__/parsers/ember-template-lint-parser-test.ts
  packages/core/src/analyzers/ast-analyzer.ts
  packages/core/src/analyzers/ember-template-lint-analyzer.ts
  packages/core/src/analyzers/eslint-analyzer.ts
  packages/core/src/analyzers/javascript-analyzer.ts
  packages/core/src/analyzers/json-analyzer.ts
  packages/core/src/analyzers/typescript-analyzer.ts
  packages/core/src/ast/ast-transformer.ts
  packages/core/src/data/lint.ts
  packages/core/src/data/sarif.ts
  packages/core/src/index.ts
  packages/core/src/parsers/eslint-parser.ts
  packages/core/src/types/analyzers.ts
  packages/core/src/types/cli.ts
  packages/core/src/types/parsers.ts
  packages/core/src/types/tasks.ts
  packages/plugin/src/generate-docs.ts
  packages/test-helpers/src/get-task-context.ts
Labels: breaking

#1000 Removes husky-install from prepare script
  package.json
Labels: internal

#1001 Adds new analyzer: stylelint
  packages/core/__tests__/__fixtures__/simple.css
  packages/core/__tests__/analyzers/stylelint-analyzer-test.ts
  packages/core/package.json
  packages/core/src/analyzers/stylelint-analyzer.ts
  yarn.lock
Labels: enhancement

#1002 Upgrades typescript to 4.2.4
  package.json
  packages/cli/src/api/generator.ts
  yarn.lock
Labels: dependencies

#1003 Creates DependencyAnalyzer for use in multiple tasks
  package.json
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/generators/base-generator.ts
  packages/core/__tests__/__fixtures__/package.json
  packages/core/__tests__/analyzers/dependency-analyzer-test.ts
  packages/core/package.json
  packages/core/src/analyzers/dependency-analyzer.ts
  packages/core/src/index.ts
  packages/core/src/types/dependency.ts
  packages/core/src/utils/get-package-json.ts
  yarn.lock
Labels: enhancement

#1006 Adding handlebars analyzer
  packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/core/package.json
  packages/core/src/analyzers/ast-analyzer.ts
  packages/core/src/analyzers/handlebars-analyzer.ts
  packages/core/src/index.ts
  packages/plugin/src/generate-docs.ts
  yarn.lock
Labels: enhancement

#1009 Allows for loading plugins from arbitrary directories using `--plugin-base-dir`
  packages/cli/__tests__/__utils__/fake-project.ts
  packages/cli/__tests__/cli-test.ts
  packages/cli/src/api/checkup-task-runner.ts
Labels: enhancement

#1011 Standardizing output in tasks: ember-in-repo-addons-engines-task
  packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
  packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
  packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
Labels: breaking

#1017 Adding CheckupLogBuilder to taskContext
  packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-template-lint-summary-task-test.ts
  packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
  packages/checkup-plugin-ember/src/actions/ember-template-lint-disable-actions.ts
  packages/checkup-plugin-ember/src/actions/ember-template-lint-summary-actions.ts
  packages/checkup-plugin-ember/src/actions/ember-test-types-actions.ts
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
  packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
  packages/checkup-plugin-javascript/src/actions/eslint-disable-actions.ts
  packages/checkup-plugin-javascript/src/actions/eslint-summary-actions.ts
  packages/checkup-plugin-javascript/src/actions/outdated-dependency-actions.ts
  packages/cli/package.json
  packages/cli/src/api/checkup-task-runner.ts
  packages/cli/src/generators/base-generator.ts
  packages/cli/src/get-log.ts
  packages/core/__tests__/actions-evaluator-test.ts
  packages/core/__tests__/data/sarif-log-builder-test.ts
  packages/core/package.json
  packages/core/src/config.ts
  packages/core/src/data/checkup-log-builder.ts
  packages/core/src/data/sarif-log-builder.ts
  packages/core/src/index.ts
  packages/core/src/types/tasks.ts
  packages/core/src/utils/extract-stack.ts
  packages/core/src/utils/get-version.ts
  packages/core/src/utils/repository.ts
  packages/test-helpers/src/get-task-context.ts
Labels: internal
