Repository checkupjs/checkup, pull requests merged in 2021-11, with the labels that each got.

#1129 Fixes base-task jsdoc generating invalid syntax for docs (mdx)
  packages/core/src/base-task.ts
Labels: documentation

#1130 Upgrades ember-template-lint to 3.11.0
  packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
  packages/core/package.json
  yarn.lock
Labels: enhancement

#1131 Removes @private jsdoc attribute
  packages/core/src/utils/normalize-package-name.ts
Labels: documentation

#1135 Adds valid-esm-package-task
  packages/checkup-plugin-javascript/__tests__/valid-esm-package-task-test.ts
  packages/checkup-plugin-javascript/package.json
  packages/checkup-plugin-javascript/src/index.ts
  packages/checkup-plugin-javascript/src/tasks/valid-esm-package-task.ts
  packages/core/__tests__/base-validation-task-test.ts
  packages/core/src/base-validation-task.ts
  yarn.lock
Labels: enhancement

#1137 [enhancement] Adding non-fatal errors to tasks
  packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
  packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
  packages/cli/__tests__/task-list-test.ts
  packages/cli/src/task-list.ts
  packages/core/src/analyzers/ast-analyzer.ts
  packages/core/src/base-task.ts
  packages/core/src/types/tasks.ts
Labels: enhancement, requires-doc-update

#1138 fix: Fixes v8 error thrown when running pretty formatter tests
  package.json
  packages/checkup-formatter-pretty/jest.config.js
  yarn.lock
Labels: internal
