Repository checkupjs/checkup, pull requests merged in 2021-02, with the labels that each got.

#864 Fixing task config overrides merging correctly
  packages/core/__tests__/utils/merge-lint-config-test.ts
  packages/core/src/parsers/ember-template-lint-parser.ts
  packages/core/src/parsers/eslint-parser.ts
  packages/core/src/utils/merge-lint-config.ts
Labels: bug

#881 Removing `output-map` from verbose-console-reporter
  checkup.code-workspace
  packages/checkup-plugin-ember/package.json
  packages/checkup-plugin-ember/src/hooks/register-task-reporters.ts
  packages/checkup-plugin-ember/src/reporters/ember-octane-migration-status-reporter.ts
  packages/checkup-plugin-ember/src/reporters/ember-template-lint-summary-reporter.ts
  packages/checkup-plugin-ember/src/reporters/ember-test-types-reporter.ts
  packages/checkup-plugin-javascript/package.json
  packages/checkup-plugin-javascript/src/hooks/register-task-reporters.ts
  packages/checkup-plugin-javascript/src/reporters/eslint-summary-reporter.ts
  packages/checkup-plugin-javascript/src/reporters/outdated-dependencies-reporter.ts
  packages/cli/src/reporters/verbose-console-reporter.ts
  packages/core/src/index.ts
  packages/core/src/utils/verbose-reporter-utils.ts
Labels: internal

#887 Merging info and migration commands
  packages/checkup-plugin-ember/package.json
  packages/checkup-plugin-ember/src/hooks/register-migration-tasks.ts
  packages/checkup-plugin-ember/src/hooks/register-tasks.ts
  packages/checkup-plugin-javascript/package.json
  packages/checkup-plugin-javascript/src/hooks/register-tasks.ts
  packages/cli/__tests__/commands/__snapshots__/migration-test.ts.snap
  packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
  packages/cli/__tests__/commands/checkup-test.ts
  packages/cli/__tests__/commands/info-test.ts
  packages/cli/__tests__/commands/run-error-test.ts
  packages/cli/__tests__/commands/run-test.ts
  packages/cli/src/commands/info.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/index.ts
  packages/core/__tests__/.DS_Store
Labels: breaking
