Repository checkupjs/checkup, pull requests merged in 2022-06, with the labels that each got.

#1230 Moves formatters from @checkup/ui to @checkup/cli
  packages/cli/package.json
  packages/cli/src/formatters/components/Pretty.tsx
  packages/cli/src/formatters/components/Summary.tsx
  packages/cli/src/formatters/pretty.ts
  packages/cli/src/formatters/summary.ts
  packages/ui/__tests__/pretty-test.tsx
  packages/ui/src/index.ts
Labels: internal

#1232 Adding formatter tests to cli package
  packages/cli/__tests__/formatters/pretty-test.tsx
  packages/cli/__tests__/formatters/summary-test.tsx
  packages/cli/vitest.config.ts
Labels: internal

#1234 Fix wrapping for Summary output
  packages/cli/src/formatters/components/Summary.tsx
  packages/ui/src/components/ResultsToFile.tsx
  yarn.lock
Labels: bug

#1237 Update executed tasks to use fully qualified task name
  packages/cli/__tests__/cli-test.ts
  packages/core/src/data/checkup-log-builder.ts
Labels: bug

#1243 Refactors path expansion for CLI inputs
  packages/cli/__tests__/cli-test.ts
  packages/cli/src/generators/config.ts
  packages/core/__tests__/utils/get-paths-test.ts
  packages/core/src/utils/get-paths.ts
Labels: breaking

#1244 Revert to using '.' as default when no paths provided
  packages/core/__tests__/utils/get-paths-test.ts
  packages/core/src/utils/get-paths.ts
  packages/core/src/utils/path.ts
Labels: bug

#1248 Recursively ignore build files
  packages/core/src/utils/get-paths.ts
Labels: enhancement
